// alojamiento-angular/src/app/features/admin/colaboradores/admin-colaboradores.component.ts
import { Component, inject, signal, computed, OnInit } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatDividerModule } from '@angular/material/divider';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatDialog } from '@angular/material/dialog';
import { UsuariosService } from '../../../services/usuarios.service';
import { NotificationService } from '../../../core/services/notification.service';
import { ConfirmDialogComponent } from '../../../shared/components/confirm-dialog/confirm-dialog.component';
import { LoadingSpinnerComponent } from '../../../shared/components/loading-spinner/loading-spinner.component';
import { ColaboradorItem } from '../../../core/models/usuario.model';
import { UsuarioAdmin } from '../../../core/models/auth.model';

@Component({
  selector: 'app-admin-colaboradores',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    MatButtonModule, MatIconModule, MatFormFieldModule, MatInputModule,
    MatSelectModule, MatDividerModule, MatTooltipModule,
    LoadingSpinnerComponent,
  ],
  templateUrl: './admin-colaboradores.component.html',
  styleUrl: './admin-colaboradores.component.scss',
})
export class AdminColaboradoresComponent implements OnInit {
  private readonly svc    = inject(UsuariosService);
  private readonly notify = inject(NotificationService);
  private readonly dialog = inject(MatDialog);
  private readonly fb     = inject(FormBuilder);

  readonly colaboradores = signal<ColaboradorItem[]>([]);
  readonly usuarios      = signal<UsuarioAdmin[]>([]);
  readonly loading       = signal(true);
  readonly submitting    = signal(false);
  readonly showForm      = signal(false);

  readonly colabForm = this.fb.group({
    usuarioId:     [null as number | null, Validators.required],
    nombreEmpresa: ['', [Validators.required, Validators.minLength(2)]],
    telefono:      ['', [Validators.required, Validators.pattern(/^\+?[\d\s\-]{7,15}$/)]],
  });

  readonly usuariosDisponibles = computed(() => {
    const colabIds = new Set(this.colaboradores().map(c => c.usuarioId));
    return this.usuarios().filter(u => !colabIds.has(u.usuarioId));
  });

  ngOnInit(): void {
    this.svc.getUsuarios().subscribe({ next: r => this.usuarios.set(r.datos ?? []) });
    this.cargar();
  }

  cargar(): void {
    this.loading.set(true);
    this.svc.getColaboradores().subscribe({
      next: r => this.colaboradores.set(r.datos ?? []),
      complete: () => this.loading.set(false),
      error: () => this.loading.set(false),
    });
  }

  guardar(): void {
    if (this.colabForm.invalid) { this.colabForm.markAllAsTouched(); return; }
    const raw = this.colabForm.getRawValue();
    this.submitting.set(true);
    this.svc.crearColaborador({
      usuarioId:     raw.usuarioId!,
      nombreEmpresa: raw.nombreEmpresa!,
      telefono:      raw.telefono!,
    }).subscribe({
      next: r => {
        this.colaboradores.update(list => [r.datos, ...list]);
        this.notify.success('Colaborador creado correctamente.');
        this.colabForm.reset();
        this.showForm.set(false);
      },
      error: () => this.submitting.set(false),
      complete: () => this.submitting.set(false),
    });
  }

  eliminar(c: ColaboradorItem): void {
    const ref = this.dialog.open(ConfirmDialogComponent, {
      data: {
        title: 'Eliminar colaborador',
        message: `¿Eliminar a "${c.nombreCompleto ?? c.nombreEmpresa}"? Sus propiedades quedarán sin responsable.`,
        confirmLabel: 'Eliminar',
      },
    });
    ref.afterClosed().subscribe(ok => {
      if (!ok) return;
      this.svc.eliminarColaborador(c.colaboradorId).subscribe({
        next: () => {
          this.colaboradores.update(list => list.filter(x => x.colaboradorId !== c.colaboradorId));
          this.notify.success('Colaborador eliminado.');
        },
        error: () => this.notify.error('No se pudo eliminar el colaborador.'),
      });
    });
  }
}

<div class="admin-page">
  <div class="page-header">
    <h1 class="section-title">Gestión de Colaboradores</h1>
    <button mat-flat-button color="primary" (click)="showForm.set(!showForm())">
      <mat-icon>{{ showForm() ? 'close' : 'add' }}</mat-icon>
      {{ showForm() ? 'Cancelar' : 'Nuevo Colaborador' }}
    </button>
  </div>

  <!-- Formulario nuevo colaborador -->
  @if (showForm()) {
    <div class="form-card">
      <h2 class="form-card-title">Nuevo Colaborador</h2>
      <form [formGroup]="colabForm" (ngSubmit)="guardar()" class="colab-form">

        <mat-form-field appearance="outline">
          <mat-label>Usuario</mat-label>
          <mat-icon matPrefix>person</mat-icon>
          <mat-select formControlName="usuarioId">
            @for (u of usuariosDisponibles(); track u.usuarioId) {
              <mat-option [value]="u.usuarioId">{{ u.nombreCompleto }} ({{ u.email }})</mat-option>
            }
          </mat-select>
          @if (usuariosDisponibles().length === 0) {
            <mat-hint>No hay usuarios disponibles sin colaborador asignado.</mat-hint>
          }
          @if (colabForm.get('usuarioId')?.hasError('required') && colabForm.get('usuarioId')?.touched) {
            <mat-error>Selecciona un usuario.</mat-error>
          }
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Nombre de empresa</mat-label>
          <mat-icon matPrefix>business</mat-icon>
          <input matInput formControlName="nombreEmpresa" placeholder="Hoteles Ejemplo S.A." />
          @if (colabForm.get('nombreEmpresa')?.hasError('required') && colabForm.get('nombreEmpresa')?.touched) {
            <mat-error>El nombre de empresa es obligatorio.</mat-error>
          }
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Teléfono</mat-label>
          <mat-icon matPrefix>phone</mat-icon>
          <input matInput formControlName="telefono" placeholder="+593 99 123 4567" />
          @if (colabForm.get('telefono')?.hasError('pattern') && colabForm.get('telefono')?.touched) {
            <mat-error>Formato de teléfono inválido.</mat-error>
          }
        </mat-form-field>

        <div class="form-actions">
          <button mat-stroked-button type="button" (click)="showForm.set(false)">Cancelar</button>
          <button mat-flat-button color="primary" type="submit" [disabled]="submitting()">
            {{ submitting() ? 'Guardando...' : 'Crear Colaborador' }}
          </button>
        </div>
      </form>
    </div>
  }

  @if (loading()) {
    <app-loading-spinner message="Cargando colaboradores..." />
  } @else if (colaboradores().length === 0) {
    <div class="empty-state">
      <mat-icon style="font-size:3rem;height:3rem;width:3rem">business</mat-icon>
      <h3>No hay colaboradores registrados</h3>
      <button mat-flat-button color="primary" (click)="showForm.set(true)">Agregar colaborador</button>
    </div>
  } @else {
    <div class="table-card">
      <div class="table-scroll">
        <table class="data-table">
          <thead>
            <tr>
              <th>Nombre / Empresa</th>
              <th>Email</th>
              <th>Teléfono</th>
              <th>Propiedades</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            @for (c of colaboradores(); track c.colaboradorId) {
              <tr>
                <td>
                  <div class="colab-name">{{ c.nombreCompleto ?? '—' }}</div>
                  @if (c.nombreEmpresa) {
                    <div class="colab-empresa">{{ c.nombreEmpresa }}</div>
                  }
                </td>
                <td class="text-muted">{{ c.email ?? '—' }}</td>
                <td>{{ c.telefono ?? '—' }}</td>
                <td>
                  <span class="badge badge-primary">{{ c.totalPropiedades ?? 0 }}</span>
                </td>
                <td>
                  <button mat-icon-button color="warn" (click)="eliminar(c)" matTooltip="Eliminar">
                    <mat-icon>delete</mat-icon>
                  </button>
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
      <div class="table-footer">{{ colaboradores().length }} colaborador(es)</div>
    </div>
  }
</div>

// booking-frontend/src/pages/admin/AdminColaboradores.jsx
import { useState, useEffect } from 'react';
import { HiOutlinePlus, HiOutlineOfficeBuilding } from 'react-icons/hi';
import toast from 'react-hot-toast';
import api from '../../services/api';
import './AdminLayout.css';

export default function AdminColaboradores() {
  const [colaboradores, setColaboradores] = useState([]);
  const [usuarios, setUsuarios] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  const [formData, setFormData] = useState({
    usuarioId: '',
    nombreEmpresa: '',
    telefono: ''
  });

  useEffect(() => { load(); }, []);

  const load = async () => {
    setLoading(true);
    try {
      const [colabRes, userRes] = await Promise.allSettled([
        api.get('/colaboradores'),
        api.get('/auth/usuarios')
      ]);

      if (colabRes.status === 'fulfilled') setColaboradores(colabRes.value.data.datos || []);
      
      if (userRes.status === 'fulfilled') {
        // Filtrar usuarios que tienen rol Colaborador
        const allUsers = userRes.value.data.datos || [];
        setUsuarios(allUsers.filter(u => u.rolNombre === 'Colaborador'));
      }
    } catch {
      toast.error('Error al cargar datos.');
    } finally {
      setLoading(false);
    }
  };

  const handleInputChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSubmitting(true);
    try {
      await api.post('/colaboradores', {
        usuarioId: parseInt(formData.usuarioId),
        nombreEmpresa: formData.nombreEmpresa,
        telefono: formData.telefono
      });
      toast.success('Colaborador registrado.');
      setShowForm(false);
      setFormData({ usuarioId: '', nombreEmpresa: '', telefono: '' });
      load();
    } catch (err) {
      toast.error(err.response?.data?.mensaje || 'Error al registrar.');
    } finally {
      setSubmitting(false);
    }
  };

  const handleDelete = async (id) => {
    if (!window.confirm('¿Estás seguro de eliminar este colaborador? Las propiedades podrían quedar sin dueño.')) return;
    try {
      await api.delete(`/colaboradores/${id}`);
      toast.success('Colaborador eliminado.');
      load();
    } catch { toast.error('Error al eliminar.'); }
  };

  return (
    <div>
      <div className="admin-page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h1 className="admin-page-title">Colaboradores (Socios)</h1>
          <p className="admin-page-subtitle">Gestión de socios que publican hoteles en el sistema</p>
        </div>
        <button className="btn btn-primary" onClick={() => setShowForm(!showForm)}>
          <HiOutlinePlus size={18} /> {showForm ? 'Ocultar Formulario' : 'Nuevo Socio'}
        </button>
      </div>

      {showForm && (
        <div className="card" style={{ padding: 24, marginBottom: 24, border: '1px solid var(--color-border)' }}>
          <h3 style={{ marginTop: 0, marginBottom: 20 }}>Registrar Nuevo Socio</h3>
          <form onSubmit={handleSubmit}>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 16 }}>
              <div>
                <label className="form-label">Cuenta de Usuario (Rol: Colaborador)</label>
                <select required className="input-field" name="usuarioId" value={formData.usuarioId} onChange={handleInputChange}>
                  <option value="">-- Selecciona el usuario --</option>
                  {usuarios.map(u => (
                    <option key={u.usuarioId} value={u.usuarioId}>{u.nombreCompleto || u.email}</option>
                  ))}
                </select>
                {usuarios.length === 0 && <span style={{ fontSize: '.8rem', color: 'var(--color-danger)' }}>No hay usuarios con rol "Colaborador". Asígnales el rol en Gestión de Usuarios primero.</span>}
              </div>
              <div>
                <label className="form-label">Nombre de la Empresa o Cadena</label>
                <input required type="text" className="input-field" name="nombreEmpresa" value={formData.nombreEmpresa} onChange={handleInputChange} placeholder="Ej. Hoteles Sunset S.A." />
              </div>
            </div>

            <div style={{ marginBottom: 20 }}>
              <label className="form-label">Teléfono de Contacto Comercial</label>
              <input required type="text" className="input-field" name="telefono" value={formData.telefono} onChange={handleInputChange} placeholder="+593 99 123 4567" style={{ maxWidth: 300 }} />
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 12 }}>
              <button type="button" className="btn btn-outline" onClick={() => setShowForm(false)}>Cancelar</button>
              <button type="submit" className="btn btn-primary" disabled={submitting || usuarios.length === 0}>
                {submitting ? 'Guardando...' : 'Registrar Socio'}
              </button>
            </div>
          </form>
        </div>
      )}

      <div className="admin-table-wrapper">
        <div className="admin-table-header">
          <h3 className="admin-table-title">Socios Registrados ({colaboradores.length})</h3>
        </div>
        {loading ? (
          <div style={{ padding: 40, textAlign: 'center', color: 'var(--color-text-muted)' }}>Cargando...</div>
        ) : colaboradores.length === 0 ? (
          <div style={{ padding: 40, textAlign: 'center', color: 'var(--color-text-muted)' }}>No hay colaboradores registrados.</div>
        ) : (
          <table className="admin-table">
            <thead>
              <tr>
                <th>ID Socio</th>
                <th>Usuario Relacionado</th>
                <th>Empresa / Cadena</th>
                <th>Contacto</th>
                <th>Propiedades</th>
                <th>Acciones</th>
              </tr>
            </thead>
            <tbody>
              {colaboradores.map((c) => (
                <tr key={c.colaboradorId}>
                  <td>{c.colaboradorId}</td>
                  <td style={{ fontSize: '.85rem', color: 'var(--color-text-muted)' }}>Usr ID: {c.usuarioId}</td>
                  <td>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                      <HiOutlineOfficeBuilding style={{ color: 'var(--color-primary)' }} />
                      <strong style={{ color: 'var(--color-text)' }}>{c.nombreEmpresa || c.nombreCompleto || 'N/D'}</strong>
                    </div>
                  </td>
                  <td>{c.telefono || c.email || '—'}</td>
                  <td><span className="badge badge-primary">{c.totalPropiedades || 0}</span></td>
                  <td>
                    <div className="admin-actions">
                      <button className="admin-btn-delete" onClick={() => handleDelete(c.colaboradorId)}>Eliminar</button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
