// booking-frontend/src/pages/admin/AdminHabitaciones.jsx
import { useState, useEffect } from 'react';
import { HiOutlinePlus, HiOutlineKey, HiOutlineTrash, HiOutlineSearch, HiOutlineOfficeBuilding } from 'react-icons/hi';
import toast from 'react-hot-toast';
import api from '../../services/api';
import useAuthStore from '../../store/useAuthStore';
import './AdminLayout.css';

export default function AdminHabitaciones() {
  const { user } = useAuthStore();
  const esAdmin = user?.roles?.includes('Administrador');

  const [propiedades, setPropiedades] = useState([]);
  const [propiedadSeleccionada, setPropiedadSeleccionada] = useState('');
  const [habitaciones, setHabitaciones] = useState([]);
  
  const [loading, setLoading] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  // Form State
  const [formData, setFormData] = useState({
    nombre: '',
    descripcion: '',
    capacidadAdultos: 2,
    capacidadNinos: 0,
    numBanos: 1,
    numDormitorios: 1,
    superficieM2: '',
    admiteMascotas: false,
    tieneCocina: false,
    tieneAireAcondicionado: true
  });

  useEffect(() => {
    // Cargar propiedades para el select principal
    const fetchProps = esAdmin 
      ? api.get('/propiedades/buscar?PageSize=1000')
      : user?.colaboradorId 
        ? api.get(`/propiedades/colaborador/${user.colaboradorId}`)
        : Promise.resolve({ data: { datos: [] } });

    fetchProps
      .then(res => {
        const payload = res.data.datos;
        setPropiedades(esAdmin ? (payload?.items || []) : (payload || []));
      })
      .catch(() => toast.error('Error al cargar la lista de propiedades.'));
    // eslint-disable-next-line
  }, []);

  useEffect(() => {
    if (propiedadSeleccionada) {
      buscarHabitaciones();
    } else {
      setHabitaciones([]);
      setShowForm(false);
    }
  }, [propiedadSeleccionada]);

  const buscarHabitaciones = async () => {
    setLoading(true);
    try {
      const { data } = await api.get(`/habitaciones/por-propiedad/${propiedadSeleccionada}`);
      setHabitaciones(data.datos || []);
    } catch { 
      toast.error('Error al cargar habitaciones.'); 
      setHabitaciones([]); 
    } finally { 
      setLoading(false); 
    }
  };

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!propiedadSeleccionada) return toast.error('Selecciona una propiedad primero.');

    setSubmitting(true);
    try {
      const payload = {
        ...formData,
        propiedadId: parseInt(propiedadSeleccionada),
        capacidadAdultos: parseInt(formData.capacidadAdultos),
        capacidadNinos: parseInt(formData.capacidadNinos),
        numBanos: parseInt(formData.numBanos),
        numDormitorios: parseInt(formData.numDormitorios),
        superficieM2: formData.superficieM2 ? parseInt(formData.superficieM2) : null
      };

      await api.post('/habitaciones', payload);
      toast.success('Habitación agregada exitosamente.');
      setShowForm(false);
      setFormData({
        nombre: '', descripcion: '', capacidadAdultos: 2, capacidadNinos: 0,
        numBanos: 1, numDormitorios: 1, superficieM2: '',
        admiteMascotas: false, tieneCocina: false, tieneAireAcondicionado: true
      });
      buscarHabitaciones();
    } catch (err) {
      toast.error(err.response?.data?.mensaje || 'Error al agregar la habitación.');
    } finally {
      setSubmitting(false);
    }
  };

  const eliminarHabitacion = async (id) => {
    if (!window.confirm('¿Estás seguro de eliminar esta habitación de forma lógica?')) return;
    try {
      await api.delete(`/habitaciones/${id}`);
      toast.success('Habitación eliminada.');
      buscarHabitaciones();
    } catch {
      toast.error('Error al eliminar la habitación.');
    }
  };

  return (
    <div>
      <div className="admin-page-header">
        <h1 className="admin-page-title">Habitaciones y Espacios</h1>
        <p className="admin-page-subtitle">Gestiona las habitaciones disponibles por cada propiedad</p>
      </div>

      {/* Filtro Principal */}
      <div className="card" style={{ padding: 20, marginBottom: 24, display: 'flex', gap: 16, alignItems: 'center', background: 'var(--color-bg)' }}>
        <HiOutlineSearch size={24} style={{ color: 'var(--color-primary)' }} />
        <div style={{ flex: 1 }}>
          <label className="form-label" style={{ marginBottom: 4 }}>Selecciona una Propiedad para administrar sus habitaciones</label>
          <select 
            className="input-field" 
            value={propiedadSeleccionada} 
            onChange={e => setPropiedadSeleccionada(e.target.value)}
            style={{ maxWidth: 400, fontWeight: 600 }}
          >
            <option value="">-- Buscar propiedad --</option>
            {propiedades.map(p => (
              <option key={p.propiedadId} value={p.propiedadId}>
                #{p.propiedadId} - {p.nombre} ({p.ciudad})
              </option>
            ))}
          </select>
        </div>
        {propiedadSeleccionada && (
          <button className="btn btn-primary" onClick={() => setShowForm(!showForm)}>
            <HiOutlinePlus size={18} /> {showForm ? 'Ocultar Formulario' : 'Nueva Habitación'}
          </button>
        )}
      </div>

      {/* Formulario */}
      {showForm && propiedadSeleccionada && (
        <div className="card" style={{ padding: 24, marginBottom: 24, border: '1px solid var(--color-border)' }}>
          <h3 style={{ marginTop: 0, marginBottom: 20 }}>Registrar Nueva Habitación</h3>
          <form onSubmit={handleSubmit}>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 16 }}>
              <div>
                <label className="form-label">Nombre / Etiqueta</label>
                <input required type="text" className="input-field" name="nombre" value={formData.nombre} onChange={handleInputChange} placeholder="Ej. Suite Presidencial, Habitación 101" />
              </div>
              <div>
                <label className="form-label">Superficie (m²)</label>
                <input type="number" className="input-field" name="superficieM2" value={formData.superficieM2} onChange={handleInputChange} placeholder="Opcional" />
              </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 16, marginBottom: 16 }}>
              <div>
                <label className="form-label">Adultos Máx.</label>
                <input required type="number" min="1" className="input-field" name="capacidadAdultos" value={formData.capacidadAdultos} onChange={handleInputChange} />
              </div>
              <div>
                <label className="form-label">Niños Máx.</label>
                <input required type="number" min="0" className="input-field" name="capacidadNinos" value={formData.capacidadNinos} onChange={handleInputChange} />
              </div>
              <div>
                <label className="form-label">Dormitorios</label>
                <input required type="number" min="1" className="input-field" name="numDormitorios" value={formData.numDormitorios} onChange={handleInputChange} />
              </div>
              <div>
                <label className="form-label">Baños</label>
                <input required type="number" min="1" className="input-field" name="numBanos" value={formData.numBanos} onChange={handleInputChange} />
              </div>
            </div>

            <div style={{ display: 'flex', gap: 24, marginBottom: 20, padding: '16px', background: 'var(--color-bg-alt)', borderRadius: 8 }}>
              <label style={{ display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer', fontWeight: 500 }}>
                <input type="checkbox" name="tieneAireAcondicionado" checked={formData.tieneAireAcondicionado} onChange={handleInputChange} /> A/C
              </label>
              <label style={{ display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer', fontWeight: 500 }}>
                <input type="checkbox" name="tieneCocina" checked={formData.tieneCocina} onChange={handleInputChange} /> Cocina
              </label>
              <label style={{ display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer', fontWeight: 500 }}>
                <input type="checkbox" name="admiteMascotas" checked={formData.admiteMascotas} onChange={handleInputChange} /> Mascotas
              </label>
            </div>

            <div style={{ marginBottom: 20 }}>
              <label className="form-label">Descripción Detallada</label>
              <textarea required className="input-field" name="descripcion" value={formData.descripcion} onChange={handleInputChange} rows={2} placeholder="Características especiales de la habitación..."></textarea>
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 12 }}>
              <button type="button" className="btn btn-outline" onClick={() => setShowForm(false)}>Cancelar</button>
              <button type="submit" className="btn btn-primary" disabled={submitting}>
                {submitting ? 'Guardando...' : 'Guardar Habitación'}
              </button>
            </div>
          </form>
        </div>
      )}

      {/* Lista de Habitaciones */}
      {propiedadSeleccionada && (
        <div className="admin-table-wrapper">
          <div className="admin-table-header">
            <h3 className="admin-table-title">Inventario de Habitaciones ({habitaciones.length})</h3>
          </div>
          {loading ? (
            <div style={{ padding: 40, textAlign: 'center', color: 'var(--color-text-muted)' }}>Cargando...</div>
          ) : habitaciones.length === 0 ? (
            <div style={{ padding: 40, textAlign: 'center', color: 'var(--color-text-muted)' }}>
              Esta propiedad no tiene habitaciones registradas.
            </div>
          ) : (
            <table className="admin-table">
              <thead>
                <tr>
                  <th>Nombre</th>
                  <th>Capacidad</th>
                  <th>Distribución</th>
                  <th>A/C</th>
                  <th>Cocina</th>
                  <th>Mascotas</th>
                  <th>Acciones</th>
                </tr>
              </thead>
              <tbody>
                {habitaciones.map((h) => (
                  <tr key={h.habitacionId}>
                    <td>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                        <HiOutlineKey size={16} style={{ color: 'var(--color-accent)' }} />
                        <strong style={{ color: 'var(--color-primary)' }}>{h.nombre}</strong>
                      </div>
                      {h.superficieM2 && <span style={{ fontSize: '.8rem', color: 'var(--color-text-muted)' }}>{h.superficieM2} m²</span>}
                    </td>
                    <td>{h.capacidadAdultos} Ad., {h.capacidadNinos} Ni.</td>
                    <td>{h.numDormitorios} Dorm. / {h.numBanos} Baño(s)</td>
                    <td>{h.tieneAireAcondicionado ? '✓' : '—'}</td>
                    <td>{h.tieneCocina ? '✓' : '—'}</td>
                    <td>{h.admiteMascotas ? '✓' : '—'}</td>
                    <td>
                      <button 
                        className="admin-btn-delete"
                        onClick={() => eliminarHabitacion(h.habitacionId)}
                        title="Eliminar habitación"
                      >
                        <HiOutlineTrash size={16} />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}
      
      {!propiedadSeleccionada && (
        <div style={{ padding: 60, textAlign: 'center', color: 'var(--color-text-muted)', border: '2px dashed var(--color-border)', borderRadius: 12 }}>
          <HiOutlineOfficeBuilding size={48} style={{ opacity: 0.5, marginBottom: 16 }} />
          <h3>Ninguna Propiedad Seleccionada</h3>
          <p>Usa el buscador superior para seleccionar un hotel y gestionar sus habitaciones.</p>
        </div>
      )}
    </div>
  );
}

// alojamiento-angular/src/app/features/admin/habitaciones/admin-habitaciones.component.ts
import { Component, inject, signal, OnInit } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatDividerModule } from '@angular/material/divider';
import { MatTooltipModule } from '@angular/material/tooltip';
import { CurrencyPipe } from '@angular/common';
import { MatDialog } from '@angular/material/dialog';
import { AlojamientosService } from '../../../services/alojamientos.service';
import { AuthStore } from '../../../core/store/auth.store';
import { NotificationService } from '../../../core/services/notification.service';
import { ConfirmDialogComponent } from '../../../shared/components/confirm-dialog/confirm-dialog.component';
import { LoadingSpinnerComponent } from '../../../shared/components/loading-spinner/loading-spinner.component';
import { HabitacionItem, PropiedadItem } from '../../../core/models/alojamiento.model';

@Component({
  selector: 'app-admin-habitaciones',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    CurrencyPipe,
    MatButtonModule, MatIconModule, MatFormFieldModule, MatInputModule,
    MatSelectModule, MatCheckboxModule, MatDividerModule, MatTooltipModule,
    LoadingSpinnerComponent,
  ],
  templateUrl: './admin-habitaciones.component.html',
  styleUrl: './admin-habitaciones.component.scss',
})
export class AdminHabitacionesComponent implements OnInit {
  private readonly svc    = inject(AlojamientosService);
  private readonly auth   = inject(AuthStore);
  private readonly notify = inject(NotificationService);
  private readonly dialog = inject(MatDialog);
  private readonly fb     = inject(FormBuilder);

  readonly propiedades  = signal<PropiedadItem[]>([]);
  readonly habitaciones = signal<HabitacionItem[]>([]);
  readonly selectedProp = signal<number | null>(null);
  readonly loading      = signal(false);
  readonly submitting   = signal(false);
  readonly showForm     = signal(false);

  readonly habForm = this.fb.group({
    nombre:                ['', [Validators.required, Validators.minLength(2)]],
    descripcion:           [''],
    capacidadAdultos:      [2, [Validators.required, Validators.min(1)]],
    capacidadNinos:        [0, Validators.min(0)],
    numBanos:              [1, [Validators.required, Validators.min(1)]],
    numDormitorios:        [1, [Validators.required, Validators.min(1)]],
    superficieM2:          [null as number | null],
    precioPorNoche:        [null as number | null, [Validators.required, Validators.min(1)]],
    admiteMascotas:        [false],
    tieneCocina:           [false],
    tieneAireAcondicionado:[false],
  });

  ngOnInit(): void {
    const colaboradorId = this.auth.user()?.colaboradorId;
    if (colaboradorId && !this.auth.isAdmin()) {
      this.svc.getPropiedadesByColaborador(colaboradorId).subscribe({
        next: r => this.propiedades.set(r.datos ?? []),
      });
    } else {
      this.svc.buscarPropiedades({ PageSize: 200 }).subscribe({
        next: r => this.propiedades.set(r.datos?.items ?? []),
      });
    }
  }

  seleccionarPropiedad(propiedadId: number): void {
    this.selectedProp.set(propiedadId);
    this.loading.set(true);
    this.svc.getHabitacionesByPropiedad(propiedadId).subscribe({
      next: r => this.habitaciones.set(r.datos ?? []),
      complete: () => this.loading.set(false),
      error: () => this.loading.set(false),
    });
  }

  guardar(): void {
    if (this.habForm.invalid) { this.habForm.markAllAsTouched(); return; }
    const propiedadId = this.selectedProp();
    if (!propiedadId) { this.notify.error('Selecciona una propiedad primero.'); return; }

    const raw = this.habForm.getRawValue();
    this.submitting.set(true);
    this.svc.crearHabitacion({
      propiedadId,
      nombre:                raw.nombre!,
      descripcion:           raw.descripcion ?? '',
      capacidadAdultos:      raw.capacidadAdultos!,
      capacidadNinos:        raw.capacidadNinos ?? 0,
      numBanos:              raw.numBanos!,
      numDormitorios:        raw.numDormitorios!,
      superficieM2:          raw.superficieM2 ?? null,
      admiteMascotas:        raw.admiteMascotas ?? false,
      tieneCocina:           raw.tieneCocina ?? false,
      tieneAireAcondicionado: raw.tieneAireAcondicionado ?? false,
    }).subscribe({
      next: r => {
        this.habitaciones.update(list => [...list, r.datos]);
        this.notify.success('Habitación creada correctamente.');
        this.habForm.reset({ capacidadAdultos: 2, capacidadNinos: 0, numBanos: 1, numDormitorios: 1 });
        this.showForm.set(false);
      },
      error: () => this.submitting.set(false),
      complete: () => this.submitting.set(false),
    });
  }

  eliminar(h: HabitacionItem): void {
    const ref = this.dialog.open(ConfirmDialogComponent, {
      data: {
        title: 'Eliminar habitación',
        message: `¿Eliminar "${h.nombre}"? Esta acción no se puede deshacer.`,
        confirmLabel: 'Eliminar',
      },
    });
    ref.afterClosed().subscribe(ok => {
      if (!ok) return;
      this.svc.eliminarHabitacion(h.habitacionId).subscribe({
        next: () => {
          this.habitaciones.update(list => list.filter(x => x.habitacionId !== h.habitacionId));
          this.notify.success('Habitación eliminada.');
        },
        error: () => this.notify.error('No se pudo eliminar la habitación.'),
      });
    });
  }
}

<div class="admin-page">
  <div class="page-header">
    <h1 class="section-title">Gestión de Habitaciones</h1>
    @if (selectedProp()) {
      <button mat-flat-button color="primary" (click)="showForm.set(!showForm())">
        <mat-icon>{{ showForm() ? 'close' : 'add' }}</mat-icon>
        {{ showForm() ? 'Cancelar' : 'Nueva Habitación' }}
      </button>
    }
  </div>

  <!-- Selector de propiedad -->
  <div class="prop-selector-card">
    <mat-form-field appearance="outline" class="prop-select-field">
      <mat-label>Selecciona una propiedad</mat-label>
      <mat-icon matPrefix>apartment</mat-icon>
      <mat-select [value]="selectedProp()" (selectionChange)="seleccionarPropiedad($event.value)">
        @for (p of propiedades(); track p.propiedadId) {
          <mat-option [value]="p.propiedadId">{{ p.nombre }}</mat-option>
        }
      </mat-select>
    </mat-form-field>
  </div>

  <!-- Formulario nueva habitación -->
  @if (showForm() && selectedProp()) {
    <div class="form-card">
      <h2 class="form-card-title">Nueva Habitación</h2>
      <form [formGroup]="habForm" (ngSubmit)="guardar()" class="hab-form">

        <mat-form-field appearance="outline" class="span-2">
          <mat-label>Nombre</mat-label>
          <input matInput formControlName="nombre" placeholder="Suite Premium" />
          @if (habForm.get('nombre')?.hasError('required') && habForm.get('nombre')?.touched) {
            <mat-error>El nombre es obligatorio.</mat-error>
          }
        </mat-form-field>

        <mat-form-field appearance="outline" class="span-2">
          <mat-label>Descripción</mat-label>
          <textarea matInput formControlName="descripcion" rows="2"></textarea>
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Capacidad adultos</mat-label>
          <mat-icon matPrefix>person</mat-icon>
          <input matInput type="number" formControlName="capacidadAdultos" min="1" />
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Capacidad niños</mat-label>
          <mat-icon matPrefix>child_care</mat-icon>
          <input matInput type="number" formControlName="capacidadNinos" min="0" />
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Nº Dormitorios</mat-label>
          <mat-icon matPrefix>bed</mat-icon>
          <input matInput type="number" formControlName="numDormitorios" min="1" />
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Nº Baños</mat-label>
          <mat-icon matPrefix>bathroom</mat-icon>
          <input matInput type="number" formControlName="numBanos" min="1" />
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Superficie (m²)</mat-label>
          <input matInput type="number" formControlName="superficieM2" min="1" />
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Precio por noche (USD)</mat-label>
          <mat-icon matPrefix>attach_money</mat-icon>
          <input matInput type="number" formControlName="precioPorNoche" min="1" />
          @if (habForm.get('precioPorNoche')?.hasError('required') && habForm.get('precioPorNoche')?.touched) {
            <mat-error>El precio es obligatorio.</mat-error>
          }
        </mat-form-field>

        <div class="checks-row span-2">
          <mat-checkbox formControlName="admiteMascotas" color="primary">Admite mascotas</mat-checkbox>
          <mat-checkbox formControlName="tieneCocina" color="primary">Cocina</mat-checkbox>
          <mat-checkbox formControlName="tieneAireAcondicionado" color="primary">Aire acondicionado</mat-checkbox>
        </div>

        <div class="form-actions span-2">
          <button mat-stroked-button type="button" (click)="showForm.set(false)">Cancelar</button>
          <button mat-flat-button color="primary" type="submit" [disabled]="submitting()">
            {{ submitting() ? 'Guardando...' : 'Crear Habitación' }}
          </button>
        </div>
      </form>
    </div>
  }

  @if (!selectedProp()) {
    <div class="empty-state">
      <mat-icon style="font-size:3rem;height:3rem;width:3rem">apartment</mat-icon>
      <h3>Selecciona una propiedad para ver sus habitaciones</h3>
    </div>
  } @else if (loading()) {
    <app-loading-spinner message="Cargando habitaciones..." />
  } @else if (habitaciones().length === 0) {
    <div class="empty-state">
      <mat-icon style="font-size:3rem;height:3rem;width:3rem">king_bed</mat-icon>
      <h3>No hay habitaciones en esta propiedad</h3>
      <button mat-flat-button color="primary" (click)="showForm.set(true)">Agregar habitación</button>
    </div>
  } @else {
    <div class="table-card">
      <div class="table-scroll">
        <table class="data-table">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Capacidad</th>
              <th>Dorm / Baños</th>
              <th>Superficie</th>
              <th>Precio / noche</th>
              <th>Extras</th>
              <th>Estado</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            @for (h of habitaciones(); track h.habitacionId) {
              <tr>
                <td class="font-semibold">{{ h.nombre }}</td>
                <td>{{ h.capacidadAdultos }}A / {{ h.capacidadNinos }}N</td>
                <td>{{ h.numDormitorios }} / {{ h.numBanos }}</td>
                <td>{{ h.superficieM2 ? h.superficieM2 + ' m²' : '—' }}</td>
                <td class="font-semibold text-accent">
                  {{ h.precioPorNoche ? (h.precioPorNoche | currency:'USD':'symbol':'1.0-0') : '—' }}
                </td>
                <td>
                  <div class="extras-row">
                    @if (h.admiteMascotas)         { <span class="extra-chip">Mascotas</span> }
                    @if (h.tieneCocina)            { <span class="extra-chip">Cocina</span> }
                    @if (h.tieneAireAcondicionado) { <span class="extra-chip">A/C</span> }
                  </div>
                </td>
                <td>
                  <span class="badge" [class]="h.estado ? 'badge-success' : 'badge-danger'">
                    {{ h.estado ? 'Activa' : 'Inactiva' }}
                  </span>
                </td>
                <td>
                  <button mat-icon-button color="warn" (click)="eliminar(h)" matTooltip="Eliminar">
                    <mat-icon>delete</mat-icon>
                  </button>
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
      <div class="table-footer">{{ habitaciones().length }} habitación(es)</div>
    </div>
  }
</div>
