// booking-frontend/src/pages/admin/AdminPropiedades.jsx
import { useState, useEffect } from 'react';
import { HiOutlinePlus, HiOutlineOfficeBuilding, HiOutlineLocationMarker } from 'react-icons/hi';
import toast from 'react-hot-toast';
import api from '../../services/api';
import useAuthStore from '../../store/useAuthStore';
import './AdminLayout.css';

export default function AdminPropiedades() {
  const { user } = useAuthStore();
  const esAdmin = user?.roles?.includes('Administrador');
  const esColaborador = user?.roles?.includes('Colaborador');

  const [propiedades, setPropiedades] = useState([]);
  const [ciudades, setCiudades] = useState([]);
  const [tipos, setTipos] = useState([]);
  const [colaboradores, setColaboradores] = useState([]);
  
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  // Form State
  const [formData, setFormData] = useState({
    nombre: '',
    descripcion: '',
    direccion: '',
    ciudadId: '',
    tipoAlojamientoId: '',
    estrellas: 3,
    admiteMascotas: false,
    colaboradorId: esAdmin ? '' : (user?.colaboradorId || '')
  });

  useEffect(() => { 
    loadData(); 
    // eslint-disable-next-line
  }, []);

  const loadData = async () => {
    setLoading(true);
    try {
      const [propRes, ciudRes, tipoRes, colabRes] = await Promise.allSettled([
        esAdmin ? api.get('/propiedades/buscar') : api.get(`/propiedades/colaborador/${user?.colaboradorId}`),
        api.get('/maestros/ciudades'),
        api.get('/maestros/tipos-alojamiento'),
        esAdmin ? api.get('/colaboradores') : Promise.resolve({ data: { datos: [] } })
      ]);

      if (propRes.status === 'fulfilled') {
        const payload = propRes.value.data.datos;
        setPropiedades(esAdmin ? (payload?.items || []) : (payload || []));
      }
      if (ciudRes.status === 'fulfilled') setCiudades(ciudRes.value.data.datos || []);
      if (tipoRes.status === 'fulfilled') setTipos(tipoRes.value.data.datos || []);
      if (colabRes.status === 'fulfilled' && esAdmin) setColaboradores(colabRes.value.data.datos || []);
    } catch {
      toast.error('Error al cargar datos maestros.');
    } finally {
      setLoading(false);
    }
  };

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSubmitting(true);
    try {
      const payload = {
        ...formData,
        ciudadId: parseInt(formData.ciudadId),
        tipoAlojamientoId: parseInt(formData.tipoAlojamientoId),
        estrellas: parseInt(formData.estrellas),
        colaboradorId: esAdmin ? parseInt(formData.colaboradorId) : user?.colaboradorId
      };

      await api.post('/propiedades', payload);
      toast.success('Propiedad creada exitosamente.');
      setShowForm(false);
      setFormData({
        nombre: '', descripcion: '', direccion: '', ciudadId: '', 
        tipoAlojamientoId: '', estrellas: 3, admiteMascotas: false, colaboradorId: ''
      });
      loadData();
    } catch (err) {
      toast.error(err.response?.data?.mensaje || 'Error al crear la propiedad.');
    } finally {
      setSubmitting(false);
    }
  };

  const toggleEstado = async (id, estadoActual) => {
    const nuevoEstado = estadoActual === 'Activa' ? 'Inactiva' : 'Activa';
    try {
      await api.patch(`/propiedades/${id}/estado`, { nuevoEstado });
      toast.success(`Propiedad marcada como ${nuevoEstado}`);
      loadData();
    } catch {
      toast.error('Error al cambiar el estado.');
    }
  };

  return (
    <div>
      <div className="admin-page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h1 className="admin-page-title">Propiedades</h1>
          <p className="admin-page-subtitle">Gestión del inventario de hoteles y alojamientos</p>
        </div>
        <button className="btn btn-primary" onClick={() => setShowForm(!showForm)}>
          <HiOutlinePlus size={18} /> {showForm ? 'Ocultar Formulario' : 'Nueva Propiedad'}
        </button>
      </div>

      {showForm && (
        <div className="card" style={{ padding: 24, marginBottom: 24, border: '1px solid var(--color-border)' }}>
          <h3 style={{ marginTop: 0, marginBottom: 20 }}>Registrar Nueva Propiedad</h3>
          <form onSubmit={handleSubmit}>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 16 }}>
              <div>
                <label className="form-label">Nombre de la Propiedad</label>
                <input required type="text" className="input-field" name="nombre" value={formData.nombre} onChange={handleInputChange} placeholder="Ej. Hotel Paraíso" />
              </div>
              {esAdmin && (
                <div>
                  <label className="form-label">Colaborador Dueño</label>
                  <select required className="input-field" name="colaboradorId" value={formData.colaboradorId} onChange={handleInputChange}>
                    <option value="">-- Seleccionar --</option>
                    {colaboradores.map(c => <option key={c.colaboradorId} value={c.colaboradorId}>{c.nombreEmpresa || c.nombreCompleto}</option>)}
                  </select>
                </div>
              )}
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 16 }}>
              <div>
                <label className="form-label">Ciudad</label>
                <select required className="input-field" name="ciudadId" value={formData.ciudadId} onChange={handleInputChange}>
                  <option value="">-- Seleccionar --</option>
                  {ciudades.map(c => <option key={c.ciudadId} value={c.ciudadId}>{c.nombre}, {c.pais}</option>)}
                </select>
              </div>
              <div>
                <label className="form-label">Tipo de Alojamiento</label>
                <select required className="input-field" name="tipoAlojamientoId" value={formData.tipoAlojamientoId} onChange={handleInputChange}>
                  <option value="">-- Seleccionar --</option>
                  {tipos.map(t => <option key={t.tipoAlojamientoId} value={t.tipoAlojamientoId}>{t.nombre}</option>)}
                </select>
              </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 16, marginBottom: 16 }}>
              <div>
                <label className="form-label">Dirección Exacta</label>
                <input required type="text" className="input-field" name="direccion" value={formData.direccion} onChange={handleInputChange} />
              </div>
              <div>
                <label className="form-label">Estrellas</label>
                <select className="input-field" name="estrellas" value={formData.estrellas} onChange={handleInputChange}>
                  {[1,2,3,4,5].map(n => <option key={n} value={n}>{n} Estrellas</option>)}
                </select>
              </div>
              <div style={{ display: 'flex', alignItems: 'flex-end', paddingBottom: 10 }}>
                <label style={{ display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer' }}>
                  <input type="checkbox" name="admiteMascotas" checked={formData.admiteMascotas} onChange={handleInputChange} />
                  Admite Mascotas
                </label>
              </div>
            </div>

            <div style={{ marginBottom: 20 }}>
              <label className="form-label">Descripción</label>
              <textarea required className="input-field" name="descripcion" value={formData.descripcion} onChange={handleInputChange} rows={3}></textarea>
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 12 }}>
              <button type="button" className="btn btn-outline" onClick={() => setShowForm(false)}>Cancelar</button>
              <button type="submit" className="btn btn-primary" disabled={submitting}>
                {submitting ? 'Guardando...' : 'Guardar Propiedad'}
              </button>
            </div>
          </form>
        </div>
      )}

      <div className="admin-table-wrapper">
        <div className="admin-table-header">
          <h3 className="admin-table-title">Inventario ({propiedades.length})</h3>
        </div>
        {loading ? (
          <div style={{ padding: 40, textAlign: 'center', color: 'var(--color-text-muted)' }}>Cargando propiedades...</div>
        ) : propiedades.length === 0 ? (
          <div style={{ padding: 40, textAlign: 'center', color: 'var(--color-text-muted)' }}>No hay propiedades registradas.</div>
        ) : (
          <table className="admin-table">
            <thead>
              <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Ubicación</th>
                <th>Estrellas</th>
                <th>Estado</th>
                <th>Acciones</th>
              </tr>
            </thead>
            <tbody>
              {propiedades.map((p) => (
                <tr key={p.propiedadId}>
                  <td>{p.propiedadId}</td>
                  <td>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                      <HiOutlineOfficeBuilding size={18} style={{ color: 'var(--color-accent)' }} />
                      <strong style={{ color: 'var(--color-text)' }}>{p.nombre}</strong>
                    </div>
                  </td>
                  <td>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 4, fontSize: '.85rem' }}>
                      <HiOutlineLocationMarker size={14} /> {p.ciudad || 'N/D'}
                    </div>
                  </td>
                  <td style={{ color: '#fbbf24' }}>{'★'.repeat(p.estrellas)}</td>
                  <td>
                    <span className={`badge ${p.estado === 'Activa' ? 'badge-success' : 'badge-danger'}`}>
                      {p.estado || 'Activa'}
                    </span>
                  </td>
                  <td>
                    <button 
                      className="admin-btn-edit"
                      onClick={() => toggleEstado(p.propiedadId, p.estado || 'Activa')}
                    >
                      {p.estado === 'Activa' ? 'Desactivar' : 'Activar'}
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}

// alojamiento-angular/src/app/features/admin/propiedades/admin-propiedades.component.ts
import { Component, inject, signal, OnInit } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatDividerModule } from '@angular/material/divider';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatDialog } from '@angular/material/dialog';
import { AlojamientosService } from '../../../services/alojamientos.service';
import { AuthStore } from '../../../core/store/auth.store';
import { NotificationService } from '../../../core/services/notification.service';
import { ConfirmDialogComponent } from '../../../shared/components/confirm-dialog/confirm-dialog.component';
import { LoadingSpinnerComponent } from '../../../shared/components/loading-spinner/loading-spinner.component';
import { PropiedadItem, Ciudad, TipoAlojamiento } from '../../../core/models/alojamiento.model';

@Component({
  selector: 'app-admin-propiedades',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    MatButtonModule, MatIconModule, MatFormFieldModule, MatInputModule,
    MatSelectModule, MatCheckboxModule, MatDividerModule, MatTooltipModule,
    LoadingSpinnerComponent,
  ],
  templateUrl: './admin-propiedades.component.html',
  styleUrl: './admin-propiedades.component.scss',
})
export class AdminPropiedadesComponent implements OnInit {
  private readonly svc    = inject(AlojamientosService);
  private readonly auth   = inject(AuthStore);
  private readonly notify = inject(NotificationService);
  private readonly dialog = inject(MatDialog);
  private readonly fb     = inject(FormBuilder);

  readonly propiedades = signal<PropiedadItem[]>([]);
  readonly ciudades    = signal<Ciudad[]>([]);
  readonly tipos       = signal<TipoAlojamiento[]>([]);
  readonly loading     = signal(true);
  readonly submitting  = signal(false);
  readonly showForm    = signal(false);

  readonly propForm = this.fb.group({
    nombre:            ['', [Validators.required, Validators.minLength(3)]],
    descripcion:       ['', Validators.required],
    direccion:         ['', Validators.required],
    ciudadId:          [null as number | null, Validators.required],
    tipoAlojamientoId: [null as number | null, Validators.required],
    estrellas:         [3, [Validators.required, Validators.min(1), Validators.max(5)]],
    admiteMascotas:    [false],
  });

  ngOnInit(): void {
    this.svc.getCiudades().subscribe({ next: r => this.ciudades.set(r.datos ?? []) });
    this.svc.getTiposAlojamiento().subscribe({ next: r => this.tipos.set(r.datos ?? []) });
    this.cargar();
  }

  cargar(): void {
    this.loading.set(true);
    const colaboradorId = this.auth.user()?.colaboradorId;
    if (colaboradorId && !this.auth.isAdmin()) {
      this.svc.getPropiedadesByColaborador(colaboradorId).subscribe({
        next: r => this.propiedades.set(r.datos ?? []),
        complete: () => this.loading.set(false),
        error: () => this.loading.set(false),
      });
    } else {
      this.svc.buscarPropiedades({ PageSize: 200 }).subscribe({
        next: r => {
          const d = r.datos;
          this.propiedades.set(d?.items ?? []);
        },
        complete: () => this.loading.set(false),
        error: () => this.loading.set(false),
      });
    }
  }

  guardar(): void {
    if (this.propForm.invalid) { this.propForm.markAllAsTouched(); return; }
    const colaboradorId = this.auth.user()?.colaboradorId;
    if (!colaboradorId) { this.notify.error('No se encontró el perfil de colaborador.'); return; }

    const raw = this.propForm.getRawValue();
    this.submitting.set(true);
    this.svc.crearPropiedad({
      nombre:            raw.nombre!,
      descripcion:       raw.descripcion!,
      direccion:         raw.direccion!,
      ciudadId:          raw.ciudadId!,
      tipoAlojamientoId: raw.tipoAlojamientoId!,
      estrellas:         raw.estrellas!,
      admiteMascotas:    raw.admiteMascotas ?? false,
      colaboradorId,
    }).subscribe({
      next: r => {
        this.propiedades.update(list => [r.datos, ...list]);
        this.notify.success('Propiedad creada correctamente.');
        this.propForm.reset({ estrellas: 3, admiteMascotas: false });
        this.showForm.set(false);
      },
      error: () => this.submitting.set(false),
      complete: () => this.submitting.set(false),
    });
  }

  toggleEstado(p: PropiedadItem): void {
    const nuevoEstado = p.estado === 'Activa' ? 'Inactiva' : 'Activa';
    const ref = this.dialog.open(ConfirmDialogComponent, {
      data: {
        title: `${nuevoEstado === 'Activa' ? 'Activar' : 'Desactivar'} propiedad`,
        message: `¿Confirmas cambiar el estado de "${p.nombre}" a ${nuevoEstado}?`,
        confirmLabel: 'Sí, cambiar',
      },
    });
    ref.afterClosed().subscribe(ok => {
      if (!ok) return;
      this.svc.cambiarEstadoPropiedad(p.propiedadId, nuevoEstado).subscribe({
        next: () => {
          this.propiedades.update(list =>
            list.map(x => x.propiedadId === p.propiedadId ? { ...x, estado: nuevoEstado } : x),
          );
          this.notify.success('Estado actualizado.');
        },
      });
    });
  }

  stars(n: number): number[] { return Array.from({ length: 5 }, (_, i) => i); }
}

<div class="admin-page">
  <div class="page-header">
    <h1 class="section-title">Gestión de Propiedades</h1>
    <button mat-flat-button color="primary" (click)="showForm.set(!showForm())">
      <mat-icon>{{ showForm() ? 'close' : 'add' }}</mat-icon>
      {{ showForm() ? 'Cancelar' : 'Nueva Propiedad' }}
    </button>
  </div>

  <!-- Formulario nueva propiedad -->
  @if (showForm()) {
    <div class="form-card">
      <h2 class="form-card-title">Nueva Propiedad</h2>
      <form [formGroup]="propForm" (ngSubmit)="guardar()" class="prop-form">

        <mat-form-field appearance="outline" class="span-2">
          <mat-label>Nombre</mat-label>
          <input matInput formControlName="nombre" placeholder="Hotel Ejemplo" />
          @if (propForm.get('nombre')?.hasError('required') && propForm.get('nombre')?.touched) {
            <mat-error>El nombre es obligatorio.</mat-error>
          }
        </mat-form-field>

        <mat-form-field appearance="outline" class="span-2">
          <mat-label>Descripción</mat-label>
          <textarea matInput formControlName="descripcion" rows="3"></textarea>
        </mat-form-field>

        <mat-form-field appearance="outline" class="span-2">
          <mat-label>Dirección</mat-label>
          <mat-icon matPrefix>place</mat-icon>
          <input matInput formControlName="direccion" />
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Ciudad</mat-label>
          <mat-select formControlName="ciudadId">
            @for (c of ciudades(); track c.ciudadId) {
              <mat-option [value]="c.ciudadId">{{ c.nombre }}</mat-option>
            }
          </mat-select>
          @if (propForm.get('ciudadId')?.hasError('required') && propForm.get('ciudadId')?.touched) {
            <mat-error>Selecciona una ciudad.</mat-error>
          }
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Tipo de Alojamiento</mat-label>
          <mat-select formControlName="tipoAlojamientoId">
            @for (t of tipos(); track t.tipoAlojamientoId) {
              <mat-option [value]="t.tipoAlojamientoId">{{ t.nombre }}</mat-option>
            }
          </mat-select>
          @if (propForm.get('tipoAlojamientoId')?.hasError('required') && propForm.get('tipoAlojamientoId')?.touched) {
            <mat-error>Selecciona un tipo.</mat-error>
          }
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Estrellas</mat-label>
          <mat-select formControlName="estrellas">
            @for (i of [1,2,3,4,5]; track i) {
              <mat-option [value]="i">{{ i }} ★</mat-option>
            }
          </mat-select>
        </mat-form-field>

        <div class="form-check-row">
          <mat-checkbox formControlName="admiteMascotas" color="primary">Admite mascotas</mat-checkbox>
        </div>

        <div class="form-actions span-2">
          <button mat-stroked-button type="button" (click)="showForm.set(false)">Cancelar</button>
          <button mat-flat-button color="primary" type="submit" [disabled]="submitting()">
            {{ submitting() ? 'Guardando...' : 'Crear Propiedad' }}
          </button>
        </div>
      </form>
    </div>
  }

  @if (loading()) {
    <app-loading-spinner message="Cargando propiedades..." />
  } @else if (propiedades().length === 0) {
    <div class="empty-state">
      <mat-icon style="font-size:3rem;height:3rem;width:3rem">apartment</mat-icon>
      <h3>No hay propiedades registradas</h3>
      <button mat-flat-button color="primary" (click)="showForm.set(true)">Crear primera propiedad</button>
    </div>
  } @else {
    <div class="table-card">
      <div class="table-scroll">
        <table class="data-table">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Ciudad</th>
              <th>Tipo</th>
              <th>Estrellas</th>
              <th>Estado</th>
              <th>Pet-Friendly</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            @for (p of propiedades(); track p.propiedadId) {
              <tr>
                <td class="font-semibold">{{ p.nombre }}</td>
                <td>{{ p.ciudad ?? '—' }}</td>
                <td>{{ p.tipoAlojamiento ?? '—' }}</td>
                <td>
                  <div class="stars-inline">
                    @for (i of stars(5); track i) {
                      <mat-icon class="star-sm" [class.filled]="i < p.estrellas">star</mat-icon>
                    }
                  </div>
                </td>
                <td>
                  <span class="badge" [class]="p.estado === 'Activa' ? 'badge-success' : 'badge-danger'">
                    {{ p.estado ?? 'Activa' }}
                  </span>
                </td>
                <td>
                  @if (p.admiteMascotas) {
                    <span class="badge badge-success">Sí</span>
                  } @else {
                    <span class="badge badge-danger">No</span>
                  }
                </td>
                <td>
                  <button mat-icon-button (click)="toggleEstado(p)" [matTooltip]="p.estado === 'Activa' ? 'Desactivar' : 'Activar'">
                    <mat-icon>{{ p.estado === 'Activa' ? 'toggle_on' : 'toggle_off' }}</mat-icon>
                  </button>
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
      <div class="table-footer">{{ propiedades().length }} propiedad(es)</div>
    </div>
  }
</div>
